Algoritmo "Potencia"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/04/2021
Var
a,b,c,d,valorfinal : real


Inicio
escreval("Digite valor de a ")
leia(a)
escreval("Digite valor de b")
leia(b)
escreval("Digite valor de c")
leia(c)
escreval("Digite valor de d")
leia(d)

valorfinal<- a*a+b*b+c*c+d*d


escreva("o resultado é :",valorfinal,)


Fimalgoritmo